whonixsetup -> setup-dist

diff --git a/usr/lib/setup-dist/ft_m_2 b/usr/lib/setup-dist/ft_m_2
--- a/usr/lib/setup-dist/ft_m_2
+++ b/usr/lib/setup-dist/ft_m_2
@@ -20,7 +20,7 @@ error_handler() {
 
 trap "error_handler" ERR
 
-source "/usr/lib/whonixsetup_/shared"
+source "/usr/lib/setup-dist/shared"
 
 ## root check
 if [ "$(id -u)" != "0" ]; then
@@ -35,16 +35,16 @@ stop_tor() {
       sleep 1
 
       if [ "$exit_code" = "0" ]; then
-         dialog_wrapper --title "whonixsetup - Info" --msgbox 'The Tor process is still running. Stopping it now...' 640 480
+         dialog_wrapper --title "setup-dist - Info" --msgbox 'The Tor process is still running. Stopping it now...' 640 480
 
          exit_code="0"
          systemctl --no-pager stop tor@default || { exit_code="$?"; true; };
          sync
          sleep 1
 
-         dialog_wrapper --title "whonixsetup - Info" --msgbox 'Stopped the Tor process.' 640 480
+         dialog_wrapper --title "setup-dist - Info" --msgbox 'Stopped the Tor process.' 640 480
       else
-         dialog_wrapper --title "whonixsetup - Info" --msgbox 'The Tor process was already stopped.' 640 480
+         dialog_wrapper --title "setup-dist - Info" --msgbox 'The Tor process was already stopped.' 640 480
       fi
 }
 
@@ -52,7 +52,7 @@ MSG="
 Do you want to disable Tor networking?
 "
 
-TITLE="whonixsetup - Disable Tor Networking"
+TITLE="setup-dist - Disable Tor Networking"
 
 exit_code="0"
 dialog_wrapper --title "$TITLE" --yesno "$MSG" 640 480 || { exit_code="$?"; true; };
@@ -71,26 +71,26 @@ fi
 python3 -c 'from tor_control_panel import tor_status; tor_status.set_disabled()' >/dev/null 2>&1  || { exit_code="$?" ; true; };
 
 if [ "$exit_code" = "0" ]; then
-   true "INFO: Ok, exit 1, so whonixsetup will end."
-   dialog_wrapper --title "whonixsetup - Success!" --msgbox 'Tor networking has been disabled.
+   true "INFO: Ok, exit 1, so setup-dist will end."
+   dialog_wrapper --title "setup-dist - Success!" --msgbox 'Tor networking has been disabled.
 
-Note: whonixsetup disables Tor networking by writing "DisableNetwork 1" to /usr/local/etc/torrc.d/40_tor_control_panel.conf
+Note: setup-dist disables Tor networking by writing "DisableNetwork 1" to /usr/local/etc/torrc.d/40_tor_control_panel.conf
 ' 640 480
-   ## Signal for whonixsetup to break the while loop.
+   ## Signal for setup-dist to break the while loop.
    exit 1
 else
-   dialog_wrapper --title "whonixsetup - ERROR!" --msgbox 'Tor networking could not be disabled. Please report this bug!
+   dialog_wrapper --title "setup-dist - ERROR!" --msgbox 'Tor networking could not be disabled. Please report this bug!
 
-Note: whonixsetup tried to disable Tor networking by writing "DisableNetwork 1" to /usr/local/etc/torrc.d/40_tor_control_panel.conf but was unable to.
+Note: setup-dist tried to disable Tor networking by writing "DisableNetwork 1" to /usr/local/etc/torrc.d/40_tor_control_panel.conf but was unable to.
 ' 640 480
 
-   dialog_wrapper --title "whonixsetup - WARNING" --msgbox 'Trying to stop the Tor process...
+   dialog_wrapper --title "setup-dist - WARNING" --msgbox 'Trying to stop the Tor process...
 
 Warning: Since Tor networking could not be disabled in /usr/local/etc/torrc.d/40_tor_control_panel.conf, Tor will reconnect the next time you reboot or restart Tor. You can try to manually comment "DisableNetwork 0" in /usr/local/etc/torrc.d/40_tor_control_panel.conf and run "sudo service tor@default stop" to ensure that Tor will not start.
 ' 640 480
 
    stop_tor
-   true "INFO: Ok, exit 1, so whonixsetup will end."
-   ## Signal for whonixsetup to break the while loop.
+   true "INFO: Ok, exit 1, so setup-dist will end."
+   ## Signal for setup-dist to break the while loop.
    exit 1
 fi
